### ISSUE TITLE
[Suggestion] Use a text file with tab separated values

### ISSUE THREAD

**Issue by marianoag** [Open-Wine-Components/ULWGL-database#2]
Wouldn't a text file with tab separated values be better for github instead of a spreadsheet, or if it has to be a spreadsheet an online editable version (but there would have to be permissions because there are no pull requests)

**Comment by GloriousEggroll** [comment]
> Wouldn't a text file with tab separated values be better for github instead of a spreadsheet, or if it has to be a spreadsheet an online editable version (but there would have to be permissions because there are no pull requests)

it could probably be a tab separated text file. not being able to view changes in PRs without downloading the modified version is not great. We didnt want to use something like google spreadsheets because it means having to use that in addition to github, but having to have a separate application to open the spreadsheet has the same problem.

my concern with a tab separated text file is some people cant tell their tabs from their spaces and the file has to be parsed by a script before being imported into an sql database -- and thats going to be automated. i dont want that getting regularly tripped up

**Comment by marianoag** [comment]
CSV Then? or slash or any other character.

Or now that i think about it: why not JSON?

**Comment by GloriousEggroll** [comment]
closing, todo added for switch to csv here https://github.com/Open-Wine-Components/ULWGL-database/issues/4
